### Get all contacts
###.REST: Es un archivo de texto que contiene todas tus requests escritas en formato REST
###.REST: It is a text file that contains all your requests written in REST format.
GET http://localhost:8080/contacts
Content-Type: application/json

###

### Get a contact by ID (replace the id later)
GET http://localhost:8080/contacts/68b82e66df7238f6c9ebc99c
Content-Type: application/json

###

### Create a new contact
POST http://localhost:8080/contacts
Content-Type: application/json

{
  "name": "Jung Hoseok",
  "email": "jung.hoseok@example.com",
  "phone": "1274359383"
}

###

### Update a contact by ID
PUT  http://localhost:8080/contacts/68b82e66df7238f6c9ebc99c
Content-Type: application/json

{
  "name": "Katherine Gonzales",
  "email": "katherine.g@example.com",
  "phone": "987654321"
}

###

### Delete a contact by ID
DELETE  http://localhost:8080/contacts/68b82e66df7238f6c9ebc99c
Content-Type: application/json
