### Obtener todos los contactos
GET http://localhost:8080/contacts
Content-Type: application/json

###

### Obtener un contacto por ID
GET http://localhost:8080/contacts/68b895a2df7238f6c9ebc99d
Content-Type: application/json

###

### Crear un nuevo contacto
POST http://localhost:8080/contacts
Content-Type: application/json

{
  "firstName": "Orejrreff",
  "lastName": "Gonzadffsdles ",
  "email": "orejas@example.com",
  "favoriteColor": "browdddn ",
  "birthday": "2022-03-12"
}

###

### Actualizar un contacto por ID
PUT http://localhost:8080/contacts/68b895a2df7238f6c9ebc99d
Content-Type: application/json

{
  "firstName": "Katherine",
  "lastName": "Gonzales",
  "email": "katherine.g@example.com",
  "favoriteColor": "Blue",
  "birthday": "1990-05-15"
}

###

### Eliminar un contacto por ID
DELETE http://localhost:8080/contacts/68cb195cc634091dcb6b3706

Content-Type: application/json
